name: Publicar Quarto para GitHub Pages

on:
  push:
    branches:
      - main # O branch principal do seu reposit√≥rio
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Renderizar Quarto
        run: quarto render

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload dos artefatos
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs' # Deve corresponder ao 'output-dir' no _quarto.yml

      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4